{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "yc-keda-external-scaler.serviceAccountName" . }}
  labels:
    {{- include "yc-keda-external-scaler.labels" . | nindent 4 }}
  {{- if or (eq (include "yc-keda-external-scaler.authMethod" .) "workloadIdentityFederation") .Values.serviceAccount.annotations }}
  annotations:
    {{- if eq (include "yc-keda-external-scaler.authMethod" .) "workloadIdentityFederation" }}
    yandex.cloud/federated-yc-service-account-id: {{ .Values.auth.workloadIdentityFederation.serviceAccountID | quote }}
    {{- end }}
    {{- with omit .Values.serviceAccount.annotations "yandex.cloud/federated-yc-service-account-id" }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
